export const cuisineTypes = [
  { id: '1', name: 'American' },
  { id: '2', name: 'Barbeque' },
  { id: '3', name: 'Indian' },
  { id: '4', name: 'Chinese' },
  { id: '5', name: 'British' },
  { id: '6', name: 'French' },
  { id: '7', name: 'Italian' },
  { id: '8', name: 'Japanese' },
  { id: '9', name: 'Mexican' },
  { id: '10', name: 'Thai' },
  { id: '11', name: 'Greek' },
  { id: '12', name: 'Spanish' },
  { id: '13', name: 'Korean' },
  { id: '14', name: 'Mediterranean' },
  { id: '15', name: 'Vietnamese' },
  { id: '16', name: 'Brazilian' },
  { id: '17', name: 'Russian' },
  { id: '18', name: 'Turkish' },
]
