export const dietaryRestrictionList = [
  { id: '1', name: 'Dairy Allergy' },
  { id: '2', name: 'Gluten Free' },
  { id: '3', name: 'Halal' },
  { id: '4', name: 'Kosher' },
  { id: '5', name: 'No Beef' },
  { id: '6', name: 'Nut Allergy' },
  { id: '7', name: 'Lactose Intolerant' },
  { id: '8', name: 'Vegetarian' },
  { id: '9', name: 'Vegan' },
  { id: '10', name: 'No Alcohol' },
  { id: '11', name: 'No Egg' },
  { id: '12', name: 'No Pork' },
  { id: '13', name: 'No Fish' },
  { id: '14', name: 'Soy-Free' },
  { id: '15', name: 'Low Carb' },
  { id: '16', name: 'Low FODMAP' },
  { id: '17', name: 'Mediterranean Diet' },
  { id: '18', name: 'Paleo Diet' },
  { id: '19', name: 'Shellfish-Free' },
]
